/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.HospitalAdmin;

import Business.Enterprise.Enterprise;
import Business.Hospital.Patient;
import Business.Organization.*;
import Business.Organization.HospitalOrganization;
//import Business.RegisterDonar.Organ;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.WorkQueue.*;
//import Business.mailAlert.SendingEmail;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.mail.MessagingException;
import javax.swing.JOptionPane;


/**
 *
 * @author BHAVIK
 */
public class RequestOrgan extends javax.swing.JPanel {

    /**
     * Creates new form RequestOrgan
     */
    JPanel userProcessContainer;
    Patient patient;
    HospitalOrganization organization;
    Enterprise enterprise;
    UserAccount userAccount;
    
    public RequestOrgan(JPanel userProcessContainer, UserAccount userAccount, Patient patient, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.organization = (HospitalOrganization)organization;
        this.patient = patient;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        //populateTable();   
    }

//     public void populateDropDown(){
////        SupplierDirectory pd = enterprise.getOrganizationDirectory().getSd();
//        //organbankdirectory;
//        //System.out.println(pd);
//        organComboBox.removeAllItems();
//        
//        
//        for(Organ o : organBankDirectory.getOrganBankDirectory()){
//            //ppp(s);
//            organComboBox.addItem(o);
//            //ppp(s);
////            for(int i = 0 ; i<s.getPersonDirectory().getPersonDirectory().size(); i++){
////            s.getPersonDirectory().getPersonDirectory().get(i).getName();
//            
//            
////            }
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        quantityComboBox = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();

        organComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kidney", "Eyes", "Liver", "Heart" }));
        organComboBox.setSelectedIndex(-1);
        organComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Doctor Work Area Panel");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        quantityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        quantityComboBox.setSelectedIndex(-1);
        quantityComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quantityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBoxActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnSubmit))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(organComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(organComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int quantity =  Integer.parseInt(String.valueOf(quantityComboBox.getSelectedItem()));
        String organName =  String.valueOf(organComboBox.getSelectedItem());
        Organization org = null;
        HospitalWorkRequest hospitalWorkRequest = new HospitalWorkRequest();
        hospitalWorkRequest.setOrganName(organName);
        hospitalWorkRequest.setPatient(patient);
        hospitalWorkRequest.setSender(userAccount);
        hospitalWorkRequest.setStatus("with Hospital Admin");
        hospitalWorkRequest.setMessage("Please Approve");
        hospitalWorkRequest.setQuantity(quantity);
        hospitalWorkRequest.setType("admin");
        hospitalWorkRequest.setHospitalName((((HospitalOrganization) organization).getOrganizationName()));
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HospitalOrganization){
                org = organization;
                
                break;
            }
        }
 

        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(hospitalWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(hospitalWorkRequest);
            //JOptionPane.showMessageDialog(null,"Request has been placed with Hospital Admin");
        }
        else{
            JOptionPane.showMessageDialog(null,"bye bye ");
        }
        
        /*
        String emailList[ ] = new String[10];
        String emailFromAddress = SendingEmail.SMTP_AUTH_USER;
        StringBuffer sb = new StringBuffer("shah.bha@husky.neu.edu ,shah.c@husky.neu.edu, gaikawad.s@husky.neu.edu , crshahc@gmail.com ,npednekar9@gmail.com ");
        StringTokenizer st = new StringTokenizer("shah.bha@husky.neu.edu ,shah.c@husky.neu.edu, gaikawad.s@husky.neu.edu , crshahc@gmail.com ,npednekar9@gmail.com ");
        int i = 0;
        while (st.hasMoreTokens()) {
            emailList[i] = st.nextToken(",");
            System.err.println(emailList[i]);
            i++;
        }
        String emailReceipeint[] = new String[i];
        for (int j = 0; j < i; j++) {
            emailReceipeint[j] = emailList[j];
            System.out.println("Actually emails are " + j);
        }


        SendingEmail smtpMailSender = new SendingEmail();
        try {
            smtpMailSender.postMail(emailReceipeint, "URGENT : Need Organ for Operation", hospitalWorkRequest.getMessage(), emailFromAddress);
        } catch (MessagingException ex) {
            //Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"ERROR      -->" +ex.toString());
            System.out.println(ex);
        } */
           JOptionPane.showMessageDialog(null,"Request has been placed with Hospital Admin");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void quantityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorMainWorkareaJPanel dwjp = (DoctorMainWorkareaJPanel) component;
        dwjp.populateTable();
        dwjp.populateReqTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void organComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox organComboBox;
    private javax.swing.JComboBox<String> quantityComboBox;
    // End of variables declaration//GEN-END:variables
}
