/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.OrganBank;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.OrganBankOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabWorkRequest;
import Business.WorkQueue.WorkRequest;
import Interface.HospitalAdmin.DienerManageRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chintan
 */
public class AssignLabJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignLabJPanel
     */
    
        private JPanel userProcessContainer;
        private OrganBankOrganization organization;
        private Enterprise enterprise;
        private UserAccount userAccount;
        private EcoSystem business;
        private WorkRequest request;
       
        
    public AssignLabJPanel(JPanel userProcessContainer, UserAccount account, OrganBankOrganization organization, Enterprise enterprise,EcoSystem business,WorkRequest request){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.request = request;
        populateLabName();
    }
    
    public void populateLabName()
    {
        for (Network network : business.getNetworkList())
        {
            for(Enterprise en : network.getEnterpriseDirectory().getEnterpriseDirectory())
            {
                for(Organization org : en.getOrganizationDirectory().getOrganizationList())
                {
                    if(org instanceof LabOrganization)
                    {
                        cb_labName.addItem(org);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_labName = new javax.swing.JComboBox();
        btn_select = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        jLabel1.setText("Lab Name :");

        btn_select.setText("Select");
        btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(cb_labName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_select)))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_labName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_select)
                    .addComponent(btn_back))
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectActionPerformed
        // TODO add your handling code here:
        LabOrganization org = (LabOrganization)cb_labName.getSelectedItem();
        request.setLabName(org.getOrganizationName());
        request.setLabStatus("pending");
        request.setSender(userAccount);
        
        LabWorkRequest labrequest = new LabWorkRequest();
        labrequest.setDonar( request.getDonar()); 
        labrequest.setOrganbankName(organization.getOrganizationName()); 
        labrequest.setLabName(org.getOrganizationName()); 
        labrequest.setSender( userAccount);
        labrequest.setMessage("Please test the organs");
        
        org.getWorkQueue().getWorkRequestList().add(labrequest);
        
        JOptionPane.showMessageDialog(null, org.getName()+" has been assigned the organ testing");
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        OrganSystemWorkRequestJPanel organSystemWorkRequestJPanel = (OrganSystemWorkRequestJPanel) component;
        organSystemWorkRequestJPanel.populateUserTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btn_selectActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_select;
    private javax.swing.JComboBox cb_labName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
