/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.OrganBank;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.OrganBankOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha Pednekar
 */
public class OrganBankAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganBankAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private OrganBankOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;

    public OrganBankAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, OrganBankOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_OrganRequest.getModel();

        model.setRowCount(0);
 
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if (request.getType().equalsIgnoreCase("OgAdmin")) {
                Object[] row = new Object[8];
                row[0] = request.getPatient().getDonor().getDonarID();
                row[1] = request.getOrganName();
                row[2] = request.getPatient().getDonor().getAge();
                row[3] = request.getQuantity();
                row[4] = request.getSender();
                row[5] = request.getReceiver() == null ? null : request.getReceiver();
                row[6] = request.getStatus();
                row[7] = request;

                model.addRow(row);
            }

            if (request.getType().equalsIgnoreCase("ogDiener")) {
                Object[] row = new Object[8];
                row[0] = request.getDonar().getDonarID();
                row[1] = "NA";
                row[2] = request.getDonar().getAge();
                row[3] = "NA";
                row[4] = request.getSender();
                row[5] = request.getReceiver() == null ? null : request.getReceiver();
                row[6] = request.getStatus();
                row[7] = request;

                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_manageOrganInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_OrganRequest = new javax.swing.JTable();
        btnHosRequest = new javax.swing.JButton();
        btn_viewOrganInventory = new javax.swing.JButton();

        btn_manageOrganInventory.setText("Add Organ Inventory");
        btn_manageOrganInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageOrganInventoryActionPerformed(evt);
            }
        });

        tbl_OrganRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person ID", "Organ", "Age", "Quantity  ", "Sender", "Reciever", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_OrganRequest);
        if (tbl_OrganRequest.getColumnModel().getColumnCount() > 0) {
            tbl_OrganRequest.getColumnModel().getColumn(0).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(1).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(2).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(3).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(4).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(5).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(6).setResizable(false);
            tbl_OrganRequest.getColumnModel().getColumn(7).setResizable(false);
        }

        btnHosRequest.setText("Process Hospital Request");
        btnHosRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHosRequestActionPerformed(evt);
            }
        });

        btn_viewOrganInventory.setText("View Organ Inventory");
        btn_viewOrganInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewOrganInventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_manageOrganInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_viewOrganInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(386, 386, 386)
                        .addComponent(btnHosRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_manageOrganInventory)
                    .addComponent(btnHosRequest))
                .addGap(35, 35, 35)
                .addComponent(btn_viewOrganInventory)
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manageOrganInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageOrganInventoryActionPerformed
        // TODO add your handling code here:
        int rowSelected = tbl_OrganRequest.getSelectedRow();
        if (rowSelected >= 0) {
            WorkRequest request = (WorkRequest) tbl_OrganRequest.getValueAt(rowSelected, 7);
            UpdateOrganRepoJPanel updateOrganRepoJPanel = new UpdateOrganRepoJPanel(userProcessContainer, userAccount, organization, enterprise, business, request);
            userProcessContainer.add("UpdateOrganRepoJPanel", updateOrganRepoJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btn_manageOrganInventoryActionPerformed

    private void btn_viewOrganInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewOrganInventoryActionPerformed
        // TODO add your handling code here:

        ViewOrganInventoryJPanel viewOrganInventoryJPanel = new ViewOrganInventoryJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("viewOrganInventoryJPanel", viewOrganInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);


    }//GEN-LAST:event_btn_viewOrganInventoryActionPerformed

    private void btnHosRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHosRequestActionPerformed
        // TODO add your handling code here:
        int rowSelected = tbl_OrganRequest.getSelectedRow();
        if (rowSelected >= 0) {
            WorkRequest request = (WorkRequest) tbl_OrganRequest.getValueAt(rowSelected, 7);
            OrganProcessJPanel organProcessJPanel = new OrganProcessJPanel(userProcessContainer, userAccount, organization, enterprise, business, request);
            userProcessContainer.add("OrganProcessJPanel", organProcessJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnHosRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHosRequest;
    private javax.swing.JButton btn_manageOrganInventory;
    private javax.swing.JButton btn_viewOrganInventory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_OrganRequest;
    // End of variables declaration//GEN-END:variables
}
