/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LabOrg;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HospitalOrganization;
import Business.Organization.LabOrganization;
import Business.UserAccount.UserAccount;
import Interface.HospitalAdmin.RegisterPatientJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chintan
 */
public class LabOrganTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabOrganTestJPanel
     */
    private JPanel userProcessContainer;
    private LabOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
        
    public LabOrganTestJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization organization, Enterprise enterprise,
            EcoSystem business){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_organTest = new javax.swing.JButton();

        btn_organTest.setText("Organ Test Request");
        btn_organTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_organTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btn_organTest)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btn_organTest)
                .addContainerGap(361, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_organTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_organTestActionPerformed
        // TODO add your handling code here:
        
                
        OrganTestRequestJPanel organTestRequestJPanel = new OrganTestRequestJPanel(userProcessContainer, userAccount, organization, enterprise, business);
        userProcessContainer.add("OrganTestRequestJPanel", organTestRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_organTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_organTest;
    // End of variables declaration//GEN-END:variables
}
