/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LabOrg;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabWorkRequest;
import Business.WorkQueue.OrganBankWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chintan
 */
public class OrganTestRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganTestRequestJPanel
     */
    
        private JPanel userProcessContainer;
    private LabOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
        
    public OrganTestRequestJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization organization, Enterprise enterprise,
            EcoSystem business){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        populateOBRequestTable();
        populateUserTable();
    }
    
    public void populateOBRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)tbl_organBankrequest.getModel();
        dtm.setRowCount(0);
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList())
        {
            if(request.getReceiver()==null)
            {
                Object[] row = new Object[4];
                row[0] = request.getOrganbankName();
                row[1] = request.getDonar().getDonarID();
                row[2] = request.getDonar().getAge();
                row[3] = request;

                dtm.addRow(row);
            }
        }
    }
    
    public void populateUserTable()
    {
        DefaultTableModel model = (DefaultTableModel)tbl_userRequest.getModel();
        model.setRowCount(0);
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
            Object[] row = new Object[8];
            row[0]= request.getOrganbankName();
            row[1] = request.getDonar().getDonarID();
            row[2] = request.getDonar().getAge();
            row[3] = request.getSender();
            row[4] = request.getStatus();
            row[5] = request;
            model.addRow(row);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_organBankrequest = new javax.swing.JTable();
        btn_Assign = new javax.swing.JButton();
        btn_processBody = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_userRequest = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();

        tbl_organBankrequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrganBank", "PersonID", "Person Age", "Message"
            }
        ));
        jScrollPane1.setViewportView(tbl_organBankrequest);

        btn_Assign.setText("Assign Me");
        btn_Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AssignActionPerformed(evt);
            }
        });

        btn_processBody.setText("Process Body");
        btn_processBody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processBodyActionPerformed(evt);
            }
        });

        tbl_userRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrganBank ", "Person ID", "Age", "Sender", "Lab Status", "Message"
            }
        ));
        jScrollPane2.setViewportView(tbl_userRequest);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_processBody))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_Assign)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Assign)
                .addGap(104, 104, 104)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_processBody)
                    .addComponent(btn_back))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_organBankrequest.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        LabWorkRequest LabWorkRequest = (LabWorkRequest) tbl_organBankrequest.getValueAt(selectedRow,3);
        LabWorkRequest.setReceiver(userAccount);
        LabWorkRequest.setStatus("work assigned to " +userAccount);
        LabWorkRequest.setMessage("pending with " + userAccount);

            //org.getWorkQueue().getWorkRequestList().add(organBankWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(LabWorkRequest);
            //JOptionPane.showMessageDialog(null,"Request has been assigned");

        populateOBRequestTable();
        populateUserTable();
    }//GEN-LAST:event_btn_AssignActionPerformed

    private void btn_processBodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processBodyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_userRequest.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        LabWorkRequest request = (LabWorkRequest) tbl_userRequest.getValueAt(selectedRow,5);
        if(!(request.getStatus()=="completed"))
        {
            UpdateOrganJPanel updateOrganJPanel = new UpdateOrganJPanel(userProcessContainer, userAccount, organization, enterprise, business, request);
            userProcessContainer.add("UpdateOrganJPanel", updateOrganJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Body already processed ");
            return;
        }

    }//GEN-LAST:event_btn_processBodyActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Assign;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_processBody;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_organBankrequest;
    private javax.swing.JTable tbl_userRequest;
    // End of variables declaration//GEN-END:variables
}
