/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LabOrg;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.OrganBankOrganization;
import Business.Organization.Organization;
import Business.RegisterDonar.Donar;
import Business.RegisterDonar.Organ;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Interface.OrganBank.OrganSystemWorkRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chintan
 */
public class UpdateOrganJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateOrganJPanel
     */
    
    private JPanel userProcessContainer;
    private LabOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private WorkRequest request;
       

        
    public UpdateOrganJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization organization, Enterprise enterprise,EcoSystem business,WorkRequest request){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_kidney = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kidneyGood = new javax.swing.JTextField();
        txt_kidneybad = new javax.swing.JTextField();
        txt_liver = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_livergood = new javax.swing.JTextField();
        txt_liverBad = new javax.swing.JTextField();
        txt_HeartBad = new javax.swing.JTextField();
        txt_eyes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Eyesgood = new javax.swing.JTextField();
        txt_EyesBad = new javax.swing.JTextField();
        txt_heart = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_HeartGood = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_EyesNA = new javax.swing.JTextField();
        txt_kidneyNA = new javax.swing.JTextField();
        txt_liverNA = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        jLabel1.setText("Organ Name");

        txt_kidney.setEditable(false);
        txt_kidney.setText("Kidney");

        jLabel2.setText("Quantity :");

        jLabel3.setText("Good");

        jLabel4.setText("Bad");

        txt_kidneyGood.setText("0");

        txt_kidneybad.setText("0");

        txt_liver.setEditable(false);
        txt_liver.setText("Liver");

        jLabel5.setText("Quantity :");

        txt_livergood.setText("0");

        txt_liverBad.setText("0");

        txt_HeartBad.setText("0");

        txt_eyes.setEditable(false);
        txt_eyes.setText("Eyes");

        jLabel6.setText("Quantity :");

        txt_Eyesgood.setText("0");

        txt_EyesBad.setText("0");

        txt_heart.setEditable(false);
        txt_heart.setText("Heart");

        jLabel7.setText("Quantity :");

        txt_HeartGood.setText("0");
        txt_HeartGood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HeartGoodActionPerformed(evt);
            }
        });

        jLabel8.setText("Not Present");

        txt_EyesNA.setText("0");

        txt_kidneyNA.setText("0");

        txt_liverNA.setText("0");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_kidney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_heart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_eyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_liver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_kidneyGood, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_kidneybad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Eyesgood, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_EyesBad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_livergood, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_liverBad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_HeartGood, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_HeartBad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_kidneyNA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_EyesNA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_liverNA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_submit)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kidneyNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_liverNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_EyesNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kidneybad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kidneyGood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_kidney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_liverBad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_livergood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_liver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_EyesBad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Eyesgood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_eyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_HeartBad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_HeartGood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_heart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_back))
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if(chackValues())
        {
            int kidneygood = Integer.parseInt(txt_kidneyGood.getText());
            int kidneybad=Integer.parseInt(txt_kidneybad.getText());
            int kidneyNa=Integer.parseInt(txt_kidneyNA.getText());

            int livergood = Integer.parseInt(txt_livergood.getText());
            int liverbad=Integer.parseInt(txt_liverBad.getText());
            int liverNa=Integer.parseInt(txt_liverNA.getText());

            int eyesgood = Integer.parseInt(txt_Eyesgood.getText());
            int eyesbad=Integer.parseInt(txt_EyesBad.getText());
            int eyesNa=Integer.parseInt(txt_EyesNA.getText());

            int heartgood = Integer.parseInt(txt_HeartGood.getText());
            int heartbad=Integer.parseInt(txt_HeartBad.getText());
            
            Donar d = request.getDonar();
            Organ kid = d.addorgan();
            kid.setOrganName(txt_kidney.getText());
            kid.setQuantity(kidneygood);
            kid.setCondition("Good");
            
            Organ liver = d.addorgan();
            liver.setOrganName(txt_liver.getText());
            liver.setQuantity(livergood);
            liver.setCondition("Good");
            
            Organ Eyes = d.addorgan();
            Eyes.setOrganName(txt_eyes.getText());
            Eyes.setQuantity(eyesgood);
            Eyes.setCondition("Good");
            
            Organ heart = d.addorgan();
            heart.setOrganName(txt_heart.getText());
            heart.setQuantity(heartgood);
            heart.setCondition("Good");
            organization.getLabOrganInventory().addGoodOrgans(d);
            
            
            Donar dbad = request.getDonar();
            Organ kid_bad = dbad.addorgan();
            kid_bad.setOrganName(txt_kidney.getText());
            kid_bad.setQuantity(kidneybad);
            kid_bad.setCondition("Bad");
            
            Organ livrbad = dbad.addorgan();
            livrbad.setOrganName(txt_liver.getText());
            livrbad.setQuantity(liverbad);
            livrbad.setCondition("Bad");
            
            Organ Eyebad = dbad.addorgan();
            Eyebad.setOrganName(txt_eyes.getText());
            Eyebad.setQuantity(eyesbad);
            Eyebad.setCondition("Bad");
            
            Organ hertbad = dbad.addorgan();
            hertbad.setOrganName(txt_heart.getText());
            hertbad.setQuantity(heartbad);
            hertbad.setCondition("Bad");
            organization.getLabOrganInventory().addBadOrgans(dbad);
            
            Donar dNA = request.getDonar();
            Organ kid_NA = dNA.addorgan();
            kid_NA.setOrganName(txt_kidney.getText());
            kid_NA.setQuantity(kidneyNa);
            kid_NA.setCondition("NA");
            
            Organ livrNA = dNA.addorgan();
            livrNA.setOrganName(txt_liver.getText());
            livrNA.setQuantity(liverNa);
            livrNA.setCondition("NA");
            
            Organ EyeNA = dNA.addorgan();
            EyeNA.setOrganName(txt_eyes.getText());
            EyeNA.setQuantity(eyesNa);
            EyeNA.setCondition("NA");
            
            
            organization.getLabOrganInventory().addNaOrgans(dNA);
            
            for(Network net : business.getNetworkList())
            {
                for(Enterprise ent : net.getEnterpriseDirectory().getEnterpriseDirectory())
                {
                    for(Organization org : ent.getOrganizationDirectory().getOrganizationList())
                    {
                        if(org instanceof OrganBankOrganization)
                        {
                            for(UserAccount ua :org.getUserAccountDirectory().getUserAccountList())
                            {
                                if(ua == request.getSender())
                                {
                                    for(WorkRequest wr : ua.getWorkQueue().getWorkRequestList())
                                    {
                                        if(wr.getDonar().getDonarID() == request.getDonar().getDonarID())
                                        {
                                            wr.setLabStatus("completed");
                                            wr.setDonar(d);
                                            wr.setStatus("Test completed");
                                            wr.setMessage("Update Inventory");
                                            request.setStatus("completed");
                                            request.setMessage("testing completed");
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            OrganTestRequestJPanel organTestRequestJPanel = (OrganTestRequestJPanel) component;
            organTestRequestJPanel.populateUserTable();
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }   
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_HeartGoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HeartGoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HeartGoodActionPerformed

    public boolean chackValues()
    {
        boolean stat= true;
        try
        {
            int kidneygood = Integer.parseInt(txt_kidneyGood.getText());
            int kidneybad=Integer.parseInt(txt_kidneybad.getText());
            int kidneyNa=Integer.parseInt(txt_kidneyNA.getText());

            int livergood = Integer.parseInt(txt_livergood.getText());
            int liverbad=Integer.parseInt(txt_liverBad.getText());
            int liverNa=Integer.parseInt(txt_liverNA.getText());

            int eyesgood = Integer.parseInt(txt_Eyesgood.getText());
            int eyesbad=Integer.parseInt(txt_EyesBad.getText());
            int eyesNa=Integer.parseInt(txt_EyesNA.getText());

            int heartgood = Integer.parseInt(txt_HeartGood.getText());
            int heartbad=Integer.parseInt(txt_HeartBad.getText());

            int kidneyQuantity = kidneygood+kidneybad+kidneyNa;
            int liverquantity = livergood+liverbad+liverNa;
            int eyesquantity = eyesgood+eyesbad+eyesNa;
            int heartQuantity = heartgood+heartbad;
            
            
            if(kidneyQuantity!=2)
            {
                JOptionPane.showMessageDialog(null, "Kidney quantity not filled properly");
                stat = false;
            }
            else if(liverquantity!=2)
            {
                JOptionPane.showMessageDialog(null, "Liver quantity not filled properly");
                stat = false;
            }
            else if(eyesquantity!=2)
            {
                JOptionPane.showMessageDialog(null, "Eyes quantity not filled properly");
                stat = false;
            }
            else if(heartQuantity!=1)
            {
                JOptionPane.showMessageDialog(null, "Heart quantity not filled properly");
                stat = false;
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Please enter the values properly");
            stat = false;
        }
        return stat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_EyesBad;
    private javax.swing.JTextField txt_EyesNA;
    private javax.swing.JTextField txt_Eyesgood;
    private javax.swing.JTextField txt_HeartBad;
    private javax.swing.JTextField txt_HeartGood;
    private javax.swing.JTextField txt_eyes;
    private javax.swing.JTextField txt_heart;
    private javax.swing.JTextField txt_kidney;
    private javax.swing.JTextField txt_kidneyGood;
    private javax.swing.JTextField txt_kidneyNA;
    private javax.swing.JTextField txt_kidneybad;
    private javax.swing.JTextField txt_liver;
    private javax.swing.JTextField txt_liverBad;
    private javax.swing.JTextField txt_liverNA;
    private javax.swing.JTextField txt_livergood;
    // End of variables declaration//GEN-END:variables
}
